### ISSUE TITLE
Regression: search on Places Organizer

### ISSUE THREAD

**Issue by pintassilgo** [piroor/xulmigemo#21]
Open this page to register in history:
http://www.ogol.com.br/team_transfers.php?id=2236&epoca_id=144

Title of the page: "Cruzeiro Esporte Clube :: Estatísticas :: Títulos :: Títulos :: História :: Gols :: Próximos Jogos :: Resultados :: Notícias :: Vídeos :: Fotos :: Time :: ogol.com.br"

Open Places Organizer (Ctrl+Shift+H)
Search for "próximos jogos". Should find (is part of the title). No results in 0.14.3, but properly finds in 0.14.2.

**Comment by piroor** [comment]
This didn't happen on environment, but I've found some errors thus fixed by 33a2fb60feab0d8cc0ebdae7fe50c32f712d7880. Is it solves this issue, or not related?

**Comment by pintassilgo** [comment]
Still occurs in 0.14.4.

Actually, I tested on another profile and worked properly. So head back to my profile and deactivated all extensions except XULMigemo, but even so the problem happens.

**Comment by pintassilgo** [comment]
I found.

`browser.urlbar.unifiedcomplete=false`

For me it's important to keep this preference with this value. Could you please fix what is preventing ignore modifiers of latin letters on url suggestions when browser.urlbar.unifiedcomplete=false?

Thanks.

**Comment by pintassilgo** [comment]
Solved. Unified complte will be mandatory starting with Fx 49, so there is no reason to care about it.

You can close this issue. Sorry for making you waste time with #21.

**Comment by piroor** [comment]
Thank you for additional information, but search in the Places Organizer for the term "próximos jogos" seems still working for me. Hmm...

**Comment by piroor** [comment]
As you mentioned, XUL/Migemo doesn't work on the location bar with the preference `browser.urlbar.unifiedcomplete=false`, it is unintentional "regression". However it is very hard to support the `browser.urlbar.unifiedcomplete=false` mode, and I know that current implementation of XUL/Migemo will die after XUL is ended by WebExtensions. So I leave this problem as "known, but unsolved". Sorry...

**Comment by pintassilgo** [comment]
Try without the accent ("proximos jogos") and unifiedcomplete=false, that way doesn't work. But OK, it's not XULMigemo fault.

**Comment by piroor** [comment]
Hmm, without accent + unifiedcomplete=false still works for me with XUL/Migemo on Nightly 49.0a1. Anyway, I close this issue for now.
